# Generated by Django 3.2.4 on 2021-07-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Barrio')),
                ('siglas', models.CharField(max_length=10, verbose_name='Siglas del barrio')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion del departamento')),
                ('valorBien', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del departamento')),
                ('nroCuartos', models.IntegerField(verbose_name='Número de cuartos')),
                ('valorMantenimiento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del mantenimiento')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barriosDepa', to='administrativo.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personasDepa', to='administrativo.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion de la casa')),
                ('valorBien', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de la casa')),
                ('nroCuartos', models.IntegerField(verbose_name='Número de cuartos')),
                ('nroPisos', models.IntegerField(verbose_name='Número de pisos')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barriosCasa', to='administrativo.barrio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personasCasa', to='administrativo.persona')),
            ],
        ),
    ]
